### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dixonary** [martindevans/CGAL_StraightSkeleton_Wrapper#2]
Hello,

I was looking at your project in order to fill a need for my University group's project. I note that your project doesn't have any kind of licensing options attached to it. 

Would we be able to use your code to interface with CGAL please? I recommend the MIT license or similar.

Best wishes!

**Comment by martindevans** [comment]
I've added [LICENSE](https://github.com/martindevans/CGAL_StraightSkeleton_Wrapper/blob/master/LICENSE) with a copy of the MIT license :)
